BulletinApp/urls.py
from . import views
from django.urls import path, include

app_name='bulletin'
urlpatterns = [
    path('', views.index, name="index"),
    
    path('register', views.register, name="register"),
    path('registerUser', views.registerUser, name="registerUser"),
    path('login', views.login, name="login"),
    path('loginUser', views.loginUser, name="loginUser"),
    path('bulletin/<str:id>', views.bulletin, name="bulletin"),
    path('bulletin-edit/', views.bulletinEdit, name="bulletin-new"),
    path('bulletin-edit/<str:bulletinId>', views.bulletinEdit, name="bulletin-edit"),
    path('post-edit/<str:bulletinId>', views.postEdit, name="post-new"),
    path('post-edit/<str:bulletinId>/<str:postId>', views.postEdit, name="post-edit"),
    path('explore/<int:distance>', views.explore, name="explore"),
    path('<str:id>', views.post, name="post"),
    path('<str:id>/comment', views.comment, name="comment"),

]

bulletin/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bulletin/', include('BulletinApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BulletinApp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    profile_picture = models.ImageField(upload_to='profile_pictures/')
    email = models.EmailField(unique=True)    
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    # Add more fields as needed

    def save(self, *args, **kwargs):
        # Set the username to be the email address
        self.username = self.email
        super().save(*args, **kwargs)

    def __str__(self):
        return self.first_name + " " + self.last_name

class Tag(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name 

class Bulletin(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    latitude = models.FloatField(blank=True)
    longitude = models.FloatField(blank=True)
    bulletin_picture = models.ImageField(upload_to='bulletin_pictures/')
    description = models.CharField(max_length=500, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    users = models.ManyToManyField(CustomUser, related_name="bulletin_list")

    def __str__(self):
        return self.title
        
class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    bulletin = models.ForeignKey(Bulletin, on_delete=models.CASCADE)
    post_picture = models.ImageField(upload_to='post_pictures/')
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title
    
class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    location = models.CharField(max_length=200)
    description = models.TextField()
    event_date_time = models.DateTimeField()
    guestlist = models.ManyToManyField(CustomUser, related_name='events_attending')

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.content[:45]
    

BulletinApp/forms.py
from django import forms
 
class BulletinForm(forms.Form):
    bulletin_name = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'form-control'}))
    pic_field = forms.ImageField()

class PostForm(forms.Form):
    post_name = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'form-control'}))
    pic_field = forms.ImageField()

BulletinApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from .models import *
from django.contrib.auth import authenticate
from geopy.distance import geodesic
from django.contrib.auth import logout
from .forms import *


# Create your views here.
def index(request):
    user = request.user
    posts = Post.objects.order_by('-pub_date')
    bulletins = user.bulletin_list.all()
    print(user)
    context = {'bulletins' : bulletins, 'posts': posts, 'user':user}
    return render(request, 'bulletin/index.html', context)

def register(request):

    return render(request, 'bulletin/register.html')

def registerUser(request):
    try:
        firstName = request.POST['first_name']
        lastName = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
    except (KeyError, User.DoesNotExist):
        return
    else:
        CustomUser.objects.create_user(first_name = firstName, last_name=lastName, email = email, password=password, username=email)
    return HttpResponseRedirect(reverse('bulletin:index'))

def login(request):
    logout(request)
    return render(request, 'bulletin/login.html')


def loginUser(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
    except (KeyError, User.DoesNotExist):
        return
    else:
        user = authenticate(username=email, password=password)
    if user is not None:
        return HttpResponseRedirect(reverse('bulletin:index'))
    else:
        return HttpResponseRedirect(reverse('bulletin:login'))

def bulletin(request, id):
    user = request.user
    bulletin = get_object_or_404(Bulletin, id__startswith=id)
    bulletins = user.bulletin_list.all()
    members = bulletin.users.all()
    posts = Post.objects.filter(bulletin=bulletin)
    context = {'bulletins': bulletins, 'posts': posts, 'bulletin': bulletin, 'members': members}
    return render(request, 'bulletin/bulletin.html', context)

def post(request, id):
    user = request.user
    bulletins = user.bulletin_list.all()
    post = get_object_or_404(Post, id__startswith=id)
    bulletin = post.bulletin
    members = bulletin.users.all()
    # print(members)
    print(bulletin)
    comments = Comment.objects.filter(post=post)
    context = {'bulletins': bulletins, 'bulletin': bulletin, 'post': post, 'comments': comments,'members': members}
    return render(request, 'bulletin/post.html', context)

def comment(request, id):
    user = request.user
    post = get_object_or_404(Post, id__startswith=id)
    try:
        content = request.POST['content']
    except (KeyError, Comment.DoesNotExist):
        return
    else:
        Comment(creator = user, content = content, post = post, pub_date = timezone.now()).save()
        return HttpResponseRedirect(reverse(f'bulletin:post', args=(id,)))
    

def explore(request, distance):
    # Retrieve the current user
    current_user = request.user

    # Get the user's location
    user_location = (current_user.latitude, current_user.longitude)

    # Calculate distances and filter bulletin boards
    bulletin_boards = []
    for bulletin in Bulletin.objects.all():
        # Get bulletin board location
        bulletin_location = (bulletin.latitude, bulletin.longitude)
        
        # Calculate distance from user to bulletin board
        bulletin_distance = geodesic(user_location, bulletin_location).miles
        
        # Check if distance is within the specified range
        if bulletin_distance <= distance:
            bulletin_boards.append((bulletin, bulletin_distance))

    # Sort bulletin boards by distance
    bulletin_boards.sort(key=lambda x: x[1])

    # Pass the sorted list of bulletin boards to the template
    context = {
        'bulletin_boards': bulletin_boards,
    }

    return render(request, 'explore.html', context) 

def bulletinEdit(request, bulletinId = None):
    user = request.user
    bulletins = user.bulletin_list.all()

    if bulletinId is not None:
        bulletin = Bulletin.objects.get(id = bulletinId)
        initial_form = {"bulletin_name": bulletin.title, "description": bulletin.description, 'pic_field': bulletin.bulletin_picture}
    else:
        initial_form = {"bulletin_name": '', "description": '', 'pic_field': ''}
    
    if request.method == "POST":
        form = BulletinForm(request.POST, request.FILES, initial=initial_form)
        if form.is_valid():
            name = form.cleaned_data.get("bulletin_name")
            description = form.cleaned_data.get("description")
            bulletin_picture = form.cleaned_data.get("pic_field")
            if (bulletinId is None):
                bulletin = Bulletin.objects.create(creator = user, title = name,bulletin_picture = bulletin_picture, description = description, latitude = 0, longitude = 0 )
                bulletin.users.add(user)
            else:
                bulletin.title = name
                bulletin.description = description
                bulletin.bulletin_picture = bulletin_picture
            bulletin.save()
            # outcome = HttpResponseRedirect(reverse('bulletin:bulletin', args=(bulletin.id)))
    else:
        form = BulletinForm(initial=initial_form)

    context = {'bulletins' : bulletins, 'user':user, 'form': form}
    outcome = render(request, 'bulletin/bulletin-edit.html', context)
    return outcome


def postEdit(request, bulletinId, postId = None):
    user = request.user
    bulletins = user.bulletin_list.all()
    bulletin = Bulletin.objects.get(id = bulletinId)
    if postId is not None:
        post = Post.objects.get(id = postId)
        initial_form = {"post_name": post.title, "description": post.content, 'pic_field': post.post_picture}
    else:
        initial_form = {"post_name": '', "description": '', 'pic_field': ''}
    
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, initial=initial_form)
        if form.is_valid():
            name = form.cleaned_data.get("post_name")
            description = form.cleaned_data.get("description")
            post_picture = form.cleaned_data.get("pic_field")
            if (postId is None):
                post = Post.objects.create(creator = user, title = name,post_picture = post_picture, content = description, bulletin = bulletin, pub_date = timezone.now() )
            else:
                post.title = name
                post.content = description
                post.post_picture = post_picture
            post.save()
    else:
        form = PostForm(initial=initial_form)

    context = {'bulletins' : bulletins, 'user':user, 'form': form}
    return render(request, 'bulletin/post-edit.html', context)

BulletinApp/templates/bulletin/bulletin-edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <title> Edit Bulletin</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="h-100">
    <!-- <div class="container"> -->
        <div class="row h-100">
            <div class="col-1 text-center side-nav flex-fill">
                <h3>Your Bulletins</h3>
                <a class="btn btn-primary" href="{% url 'bulletin:bulletin-new' %}">Create Bulletin</a>
    
                {% if bulletins %}
                {% for bulletin in bulletins %}
    
                <a id="bulletin" class="bulletin-list-item" href="{% url 'bulletin:bulletin' bulletin.id %}">
                    <div class="p-3">
                        <img src="{{ bulletin.bulletin_picture.url }}" class="rounded-circle img-fluid" />
                        <p>{{ bulletin.title }}</p>
                    </div>
                </a>
                {% endfor %}
                {% endif %}
                <!-- </div> -->
    
            </div>
        <div class=" col-10 d-flex-vertical">
            <div class="bulletin-heading h-25 p-2">
                <div class="row align-items-center h-100">
                    <div class="col-4">
                        <h1>Bulletin</h1>
                    </div>
                    <div class="col-4">
                        <h1>Location</h1>
                    </div>
                    <div class="col-4">
                        <h1>Soemthing else idk</h1>
                    </div>
                </div>
            </div>
            <div class="p-4 bulletin col d-flex-vertical">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.as_p }}
                    </div>
                    <input type="submit" value="Save" class="btn btn-primary">
                </form>
            </div>
        </div>
        <div class="col-1 side-nav text-center flex-fill">
            <h3>Members</h3>
            {% if members %}
            {% for member in members %}
            <div class="p-3 text-center ">
                <img src="{{ member.profile_picture.url }}" class="rounded-circle img-fluid" />
                <p>{{ member.first_name }} {{ member.last_name }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</body>

</html>

BulletinApp/templates/bulletin/bulletin.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <title>{{ bulletin.title }}</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="h-100">
    <!-- <div class="container"> -->
    <div class="row h-100">
        <div class="col-1 text-center side-nav flex-fill">
            <h3>Your Bulletins</h3>
            <a class="btn btn-primary" href="{% url 'bulletin:bulletin-new' %}">Create Bulletin</a>

            {% if bulletins %}
            {% for bulletin in bulletins %}

            <a id="bulletin" class="bulletin-list-item" href="{% url 'bulletin:bulletin' bulletin.id %}">
                <div class="p-3">
                    <img src="{{ bulletin.bulletin_picture.url }}" class="rounded-circle img-fluid" />
                    <p>{{ bulletin.title }}</p>
                </div>
            </a>
            {% endfor %}
            {% endif %}
            <!-- </div> -->

        </div>
        <div class=" col-10 d-flex-vertical">
            <div class="bulletin-heading h-25 p-2">
                <div class="row align-items-center h-100">
                    <div class="col-4">
                        <h1>{{ bulletin.title }}</h1>
                        <a class="btn btn-primary" href="{% url 'bulletin:bulletin-edit' bulletin.id %}">Edit Bulletin</a>

                    </div>
                    <div class="col-4">
                        <h1>Location</h1>
                    </div>
                    <div class="col-4">
                        <h1>{{ bulletin.description }}</h1>
                    </div>
                </div>
            </div>
            <div class="py-4 bulletin col d-flex-vertical">
                <div class="row px-5">
                    <a class="btn btn-primary" href="{% url 'bulletin:post-new' bulletin.id %}">Create Post</a>
                </div>
                <div class="row">

                    {% if posts %}
                    {% for post in posts %}
                    <div class="col-6">
                        <a id="post" class="bulletin-post" href="{% url 'bulletin:post' post.id %}">
                            <div class="m-3 p-2 bg-white">
                                <p class="lead p-0 m-0">{{ post.creator }}</p>
                                <h2 class="p-0 m-0">{{ post.title }}</h2>
                                <p>{{ post.pub_date }}</p>
                                <p>{{ post.content | truncatechars:200}}</p>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-1 side-nav text-center flex-fill">
            <h3>Members</h3>
            {% if members %}
            {% for member in members %}
            <div class="p-3 text-center ">
                <img src="{{ member.profile_picture.url }}" class="rounded-circle img-fluid" />
                <p>{{ member.first_name }} {{ member.last_name }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <!-- </div> -->
    </div>

</body>

</html>

BulletinApp/templates/bulletin/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <title>{{ bulletin.title }}</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="h-100">
    <!-- <div class="container"> -->
        <div class="row h-100">
            <div class="col-1 text-center side-nav flex-fill">
                <h3>Your Bulletins</h3>
                <a class="btn btn-primary" href="{% url 'bulletin:bulletin-new' %}">Create Bulletin</a>
    
                {% if bulletins %}
                {% for bulletin in bulletins %}
    
                <a id="bulletin" class="bulletin-list-item" href="{% url 'bulletin:bulletin' bulletin.id %}">
                    <div class="p-3">
                        <img src="{{ bulletin.bulletin_picture.url }}" class="rounded-circle img-fluid" />
                        <p>{{ bulletin.title }}</p>
                    </div>
                </a>
                {% endfor %}
                {% endif %}
                <!-- </div> -->
    
            </div>
        <div class=" col-10 d-flex-vertical flex-fill mx-0">
            <div class="bulletin-heading h-25 p-2">
                <div class="row align-items-center h-100">
                    <div class="col-4">
                        <h1> Bulletins </h1>
                    </div>
                    <div class="col-4">
                        <h1>Location</h1>
                    </div>
                    <div class="col-4">
                        <h1>Soemthing else idk</h1>
                    </div>
                </div>
            </div>
            <div class="py-4 bulletin d-flex-vertical align-items-center m-auto text-center flex-fill h-75">
                <div class="row">
                    <h1>Bulletin</h1>
                    <p class="lead">Choose a Bulletin to get started</p>
                </div>
            </div>
        </div>
        <div class="col-1 side-nav text-center flex-fill">
            <h3>Members</h3>
            {% if members %}
            {% for member in members %}
            <div class="p-3 text-center ">
                <img src="{{ member.profile_picture.url }}" class="rounded-circle img-fluid" />
                <p>{{ member.first_name }} {{ member.last_name }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <!-- </div> -->
    </div>

</body>

</html>

BulletinApp/templates/bulletin/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 d-flex justify-content-center">
                <form method="POST" action="{% url 'bulletin:loginUser' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Email: </label>
                        <input type="email" name="email" class="form-control" required> <br>
                        <label for="password" class="form-label">Password: </label>
                        <input type="password" name="password" class="form-control" required> <br>
                    </div>
                    <input type="submit" value="Login" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>

</body>

</html>

BulletinApp/templates/bulletin/post-edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <title> Edit Post</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="h-100">
    <!-- <div class="container"> -->
    <div class="row h-100">
        <div class="col-1 text-center side-nav flex-fill">
            <h3>Your Bulletins</h3>
            <a class="btn btn-primary" href="{% url 'bulletin:bulletin-new' %}">Create Bulletin</a>

            {% if bulletins %}
            {% for bulletin in bulletins %}

            <a id="bulletin" class="bulletin-list-item" href="{% url 'bulletin:bulletin' bulletin.id %}">
                <div class="p-3">
                    <img src="{{ bulletin.bulletin_picture.url }}" class="rounded-circle img-fluid" />
                    <p>{{ bulletin.title }}</p>
                </div>
            </a>
            {% endfor %}
            {% endif %}
            <!-- </div> -->

        </div>
        <div class=" col-10 d-flex-vertical">
            <div class="bulletin-heading h-25 p-2">
                <div class="row align-items-center h-100">
                    <div class="col-4">
                        <h1>Bulletin</h1>
                    </div>
                    <div class="col-4">
                        <h1>Location</h1>
                    </div>
                    <div class="col-4">
                        <h1>Soemthing else idk</h1>
                    </div>
                </div>
            </div>
            <div class="p-4 bulletin col d-flex-vertical">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.as_p }}
                    </div>
                    <input type="submit" value="Save" class="btn btn-primary">
                </form>
            </div>
        </div>
        <div class="col-1 side-nav text-center flex-fill">
            <h3>Members</h3>
            {% if members %}
            {% for member in members %}
            <div class="p-3 text-center ">
                <img src="{{ member.profile_picture.url }}" class="rounded-circle img-fluid" />
                <p>{{ member.first_name }} {{ member.last_name }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <!-- </div> -->
    </div>

</body>

</html>

BulletinApp/templates/bulletin/post.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ post.title }}</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <!-- <div class="container"> -->
    <div class="row d-flex-vertical">
        <div class="col-1 text-center side-nav flex-fill">
            <h3>Your Bulletins</h3>
            <a class="btn btn-primary" href="{% url 'bulletin:bulletin-new' %}">Create Bulletin</a>

            {% if bulletins %}
            {% for bulletin in bulletins %}

            <a id="bulletin" class="bulletin-list-item" href="{% url 'bulletin:bulletin' bulletin.id %}">
                <div class="p-3">
                    <img src="{{ bulletin.bulletin_picture.url }}" class="rounded-circle img-fluid" />
                    <p>{{ bulletin.title }}</p>
                </div>
            </a>
            {% endfor %}
            {% endif %}
            <!-- </div> -->

        </div>
        <div class="col-10">
            <div class="bulletin-heading p-2">
                <div class="row align-items-center h-100">
                    <div class="col-4">
                        <h1>{{ bulletin.title }}</h1>
                    </div>
                    <div class="col-4">
                        <h1>Location</h1>
                    </div>
                    <div class="col-4">
                        <h1>Soemthing else idk</h1>
                    </div>
                </div>
            </div>
            <div class="p-4 bulletin d-flex-vertical ">
                {% if post %}
                <div class="row">
                    <h1 class="d-inline-block">{{ post.title }}</h1>
                    <a class="btn btn-primary" href="{% url 'bulletin:post-edit' bulletin.id post.id%}">Edit Post</a>
                </div>
                <p class="lead p-0 m-0">{{ post.creator }}</p>
                <p>{{ post.pub_date }}</p>
                <p>{{ post.content }}</p>
                <!-- <p>{{ post.id }}</p> -->
                {% endif %}

                <h2>Comments</h2>
                <form method="POST" action="{% url 'bulletin:comment' post.id %}">
                    {% csrf_token %}
                    <textarea rows="2" cols="50" placeholder="Comment" name="content" class="form-control"></textarea>
                    <br>
                    <input type="submit" value="comment" class="btn btn-primary">
                </form>
                {% if comments %}
                {% for comment in comments %}
                <div class="border my-2 p-2 bg-white">
                    <h3>{{ comment.creator }}</h3>
                    <p>{{ comment.pub_date }}</p>
                    <p class="lead">{{ comment.content }}</p>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="col-1 side-nav text-center flex-fill">
            <h3>Members</h3>
            {% if members %}
            {% for member in members %}
            <div class="p-3 text-center ">
                <img src="{{ member.profile_picture.url }}" class="rounded-circle img-fluid" />
                <p>{{ member.first_name }} {{ member.last_name }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <!-- </div> -->
    </div>

</body>

</html>

BulletinApp/templates/bulletin/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'bulletin/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="col-10 d-flex align-items-center justify-content-center">
                <form method="POST" action="{% url 'bulletin:registerUser' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="first_name" class="form-label">First Name: </label>
                        <input type="text" name="first_name" class="form-control" required> <br>
                        <label for="last_name" class="form-label">Last Name: </label>
                        <input type="text" name="last_name" class="form-control" required> <br>
                        <label for="email" class="form-label">Email: </label>
                        <input type="email" name="email" class="form-control" required> <br>
                        <label for="password" class="form-label">Password: </label>
                        <input type="password" name="password" class="form-control" required> <br>
                    </div>
                    <input type="submit" value="Register" class="btn btn-primary">


                </form>
            </div>
        </div>
    </div>

</body>

</html>